inherit_from: ".rubocop.yml"

require:
  - rubocop-md


AllCops:
  Include:
    - '**/*.md'

Lint/DuplicateMethods:
  Enabled: false

Lint/Void:
  Exclude:
    - '**/*.md'

Lint/DuplicateMethods:
  Exclude:
    - '**/*.md'

# FIXME
Layout/InitialIndentation:
  Exclude:
    - 'CHANGELOG.md'