name: Run RSpec tests

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.5.x", "2.6.x", "2.4.x"]
        gemfile: [
          "gemfiles/railsmaster.gemfile",
          "gemfiles/activerecord6.gemfile",
          "gemfiles/activerecord42.gemfile",
          "gemfiles/default_factory_girl.gemfile",
          "gemfiles/rspec35.gemfile"
        ]
        exclude:
        - ruby: "2.6.x"
          gemfile: "gemfiles/activerecord42.gemfile"
        - ruby: "2.6.x"
          gemfile: "gemfiles/rspec35.gemfile"
        - ruby: "2.6.x"
          gemfile: "gemfiles/default_factory_girl.gemfile"
        - ruby: "2.5.x"
          gemfile: "gemfiles/railsmaster.gemfile"
        - ruby: "2.5.x"
          gemfile: "gemfiles/activerecord42.gemfile"
        - ruby: "2.5.x"
          gemfile: "gemfiles/rspec35.gemfile"
        - ruby: "2.5.x"
          gemfile: "gemfiles/default_factory_girl.gemfile"
        - ruby: "2.4.x"
          gemfile: "gemfiles/railsmaster.gemfile"
        - ruby: "2.4.x"
          gemfile: "gemfiles/activerecord6.gemfile"
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install system deps
      run: |
        sudo apt-get install libsqlite3-dev
    - name: Install Bundler
      run: |
        gem install bundler
    - name: Configure Gemfile
      run: |
        bundle config --global gemfile ${{ matrix.gemfile }}
    - name: Install Ruby deps
      run: |
        bundle install --jobs 4 --retry 3
    - name: Run RSpec
      run: |
        bundle exec rspec
  rspec-jruby:
    runs-on: ubuntu-latest
    container:
      image: jruby:9.2.8
      env:
        BUNDLE_GEMFILE: gemfiles/jruby.gemfile
    steps:
    - uses: actions/checkout@v1
    - name: Install git
      run: |
        apt-get update
        apt-get install -y --no-install-recommends git
    - name: Install deps and run RSpec
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rspec
